"""add thread_state to customers

Revision ID: 6ad4080275d7
Revises: 2c06554361d7
Create Date: 2026-07-19 14:29:55.007294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad4080275d7'
down_revision: Union[str, Sequence[str], None] = '2c06554361d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('thread_state', sa.String(length=50), nullable=True))
    op.execute("UPDATE customers SET thread_state = 'AI_CONTROLLED' WHERE thread_state IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'thread_state')
    # ### end Alembic commands ###
